AWSTemplateFormatVersion: 2010-09-09
Description: This template creates EMR

Parameters: 
  CoreInstanceCount:
    Default: '1'
    Description: Number of core instances
    Type: Number
  CoreInstanceType:
    Default: m4.large
    Description: Instance Type of the core node
    Type: String
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH to the instances
    Type: AWS::EC2::KeyPair::KeyName
    Default: babar-invesco-training
  Subnet:
    Description: Subnet ID for creating the EMR cluster
    Type: AWS::EC2::Subnet::Id
    Default: subnet-07682c2dc2510601a
  VPC:
    Description: VPC ID for creating the EMR cluster
    Type: AWS::EC2::VPC::Id
    Default: vpc-0ce18854660aa09e4
  EMRClusterName:
    Default: TestCluster
    Description: Cluster name for the EMR
    Type: String
  emrReleaseLabel:
    Default: emr-5.4.0
    AllowedValues:
    - emr-5.23.0
    - emr-5.0.0
    - emr-5.4.0
    - emr-5.16.0
    - emr-5.17.0
    Description: Release label for the EMR cluster
    Type: String
  MasterInstanceType:
    Default: m3.2xlarge
    Description: Instance Type of the master node
    Type: String
  EMRLogDir:
    Description: Log Dir for the EMR cluster
    Type: String
Resources: 
  EMRSampleCluster:
    Properties:
      Applications:
      - Name: Hadoop
      - Name: Spark
      - Name: Hive
      - Name: Livy
      Instances:
        CoreInstanceGroup:
          EbsConfiguration:
            EbsBlockDeviceConfigs:
            - VolumeSpecification:
                SizeInGB: '10'
                VolumeType: gp2
              VolumesPerInstance: '1'
            EbsOptimized: 'true'
          InstanceCount:
            Ref: CoreInstanceCount
          InstanceType:
            Ref: CoreInstanceType
          Market: ON_DEMAND
          Name: Core Instance
        Ec2KeyName:
          Ref: KeyName
        Ec2SubnetId:
          Ref: Subnet
        MasterInstanceGroup:
          InstanceCount: '1'
          InstanceType:
            Ref: MasterInstanceType
          Market: ON_DEMAND
          Name: Master Instance
        TerminationProtected: 'false'
      JobFlowRole: EMR_EC2_DefaultRole
      LogUri:
        Ref: EMRLogDir
      Name:
        Ref: EMRClusterName
      ReleaseLabel:
        Ref: emrReleaseLabel
      ServiceRole: EMR_DefaultRole
      Tags:
      - Key: Name
        Value: EMR Sample Cluster
      VisibleToAllUsers: 'true'
    Type: AWS::EMR::Cluster
