AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ClusterIdentifier:
    Description: Redshift Cluster Identifier
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/wmi-lite/staging/REDSHIFT-CLUSTER-IDENTIFIER'
  DatabaseName:
    Description: The name of the database to be created for the cluster
    Type: AWS::SSM::Parameter::Value<String>
    Default: /wmi-lite/staging/REDSHIFT-DBNAME
    #AllowedPattern: "([a-z]|[0-9])+"
  MasterUsername:
    Description: Name of master user for your cluster.
    Type: AWS::SSM::Parameter::Value<String>
    Default: /wmi-lite/staging/REDSHIFT-USER
    #AllowedPattern: "([a-z])([a-z]|[0-9])*"
  MasterUserPassword:
    Description: Master User Password
    Type: AWS::SSM::Parameter::Value<String>
    #AllowedPattern: (?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.{8,64})(^[^/"'\@]+$)
    #ConstraintDescription: Password must contain 8 to 64 printable ASCII characters excluding :\ /, ", ', \, and @. It must contain 1 uppercase letter, 1 lowercase letter, and 1 number
    Default: /wmi-lite/staging/REDSHIFT-PASSWORD
    NoEcho: 'true'
  RedshiftSecurityGroupId:
    Description: VPC Security Group Id for Redshift
    Type: AWS::SSM::Parameter::Value<AWS::EC2::SecurityGroup::Id>
    Default: /wmi-lite/staging/NAS-SECURITY-GROUPID
  RedshiftSubnetGroupName:
    Description: Subnet group name for Redshift
    Type: AWS::SSM::Parameter::Value<String>
    Default: /wmi-lite/staging/NAS-SUBNET-GROUP-NAME
  RedshiftRole:
    Description: ARN of Redshift Role
    Type: AWS::SSM::Parameter::Value<String>
    Default: /wmi-lite/staging/REDSHIFT-ADMIN-ROLE-ARN
  ClusterType:
    Description: The type of cluster
    Type: String
    Default: single-node
    AllowedValues:
    - single-node
    - multi-node
  NumberOfNodes:
    Description: The number of compute nodes in the cluster. For multi-node clusters, the NumberOfNodes parameter must be greater than 1
    Type: Number
    Default: '1'
  NodeType:
    Description: The type of node to be provisioned
    Type: String
    Default: dc2.large
    AllowedValues:
    - dc2.large
    - dc2.8xlarge
    - dc1.large
    - dc1.8xlarge
    - ds2.xlarge
    - ds2.8xlarge
  InboundTraffic:
    Description: Allow inbound traffic to the cluster from this CIDR range.
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid CIDR range of the form x.x.x.x/x.
  PortNumber:
    Description: The port number on which the cluster accepts incoming connections.
    Type: Number
    Default: '5439'
Conditions:
  IsMultiNodeCluster:
    Fn::Equals:
    - Ref: ClusterType
    - multi-node
Resources:
  RedshiftCluster:
    Type: AWS::Redshift::Cluster
    Properties:
      ClusterIdentifier: !Ref ClusterIdentifier
      ClusterType: !Ref ClusterType
      NumberOfNodes: !If [IsMultiNodeCluster, !Ref NumberOfNodes, !Ref "AWS::NoValue"]
      NodeType: !Ref NodeType
      DBName: !Ref DatabaseName
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      #ClusterParameterGroupName:
      IamRoles:
        - !Ref RedshiftRole
      VpcSecurityGroupIds:
        - !Ref RedshiftSecurityGroupId
      ClusterSubnetGroupName: !Ref RedshiftSubnetGroupName
      PubliclyAccessible: 'true'
      Port: !Ref PortNumber
# Outputs:
#   ClusterEndpoint:
#     Description: Cluster endpoint
#     Value: !Sub "${RedshiftCluster.Endpoint.Address}:${RedshiftCluster.Endpoint.Port}"
#   ClusterName:
#     Description: Name of cluster
#     Value:
#       Ref: RedshiftCluster
#   ParameterGroupName:
#     Description: Name of parameter group
#     Value:
#       Ref: RedshiftClusterParameterGroup
#   RedshiftClusterSubnetGroupName:
#     Description: Name of cluster subnet group
#     Value:
#       Ref: RedshiftClusterSubnetGroup
#   RedshiftClusterSecurityGroupName:
#     Description: Name of cluster security group
#     Value:
#       Ref: SecurityGroup