AWSTemplateFormatVersion: 2010-09-09
Description: CodePipeline Test Template
Parameters:
  CodeCommitRepoName:
    Description: Name of the Repository
    Type: String
    Default: wmi-lite-sparkjob
  CodeCommitBranchName:
    Description: Name of the Source CodeCommit Branch
    Type: String
    Default: wmi-lite-sparkjob-dev
  PipelineName:
    Description: Name of codepipeline
    Type: String
    Default: wmi-lite-codepipeline-spark
  S3KeyPath:
    Description: Name of S3 Key
    Type: String
    Default: SparkJob

Resources:
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration: 
        Status: Enabled
  iamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement:
          - 
            Effect: Allow
            Action:
              - s3:PutAnalyticsConfiguration
              - s3:PutAccelerateConfiguration
              - s3:DeleteObjectVersion
              - codecommit:GetTree
              - s3:RestoreObject
              - s3:CreateBucket
              - codecommit:GetBlob
              - codecommit:GetReferences
              - s3:PutEncryptionConfiguration
              - s3:ReplicateObject
              - codecommit:GetCommentsForComparedCommit
              - codecommit:GetCommit
              - s3:DeleteBucketWebsite
              - codecommit:GetComment
              - s3:AbortMultipartUpload
              - codecommit:GetCommitHistory
              - codecommit:GetCommitsFromMergeBase
              - s3:PutLifecycleConfiguration
              - codecommit:DescribePullRequestEvents
              - s3:DeleteObject
              - s3:DeleteBucket
              - s3:PutBucketVersioning
              - codecommit:GetPullRequest
              - codecommit:GetRepositoryTriggers
              - s3:PutMetricsConfiguration
              - s3:PutReplicationConfiguration
              - codecommit:GitPull
              - codecommit:BatchGetRepositories
              - codecommit:GetCommentsForPullRequest
              - s3:PutBucketCORS
              - codecommit:GetObjectIdentifier
              - codecommit:CancelUploadArchive
              - codecommit:GetFolder
              - s3:PutInventoryConfiguration
              - codecommit:BatchGetPullRequests
              - codecommit:GetFile
              - s3:PutObject
              - s3:PutBucketNotification
              - codecommit:GetUploadArchiveStatus
              - s3:PutBucketWebsite
              - s3:PutBucketRequestPayment
              - codecommit:GetDifferences
              - s3:PutBucketLogging
              - codecommit:GetRepository
              - codecommit:GetBranch
              - codecommit:GetMergeConflicts
              - s3:ReplicateDelete
            Resource:
              - arn:aws:s3:::haider-ali-invesco-assignment/*
              - arn:aws:s3:::haider-ali-invesco-assignment
              - arn:aws:codecommit:us-east-1:585091576682:wmi-lite-sparkjob
  codepipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Ref PipelineName
      RoleArn: !GetAtt iamRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref s3Bucket
      Stages: 
        - 
          Name: sourceCodeCommitStage
          Actions:
            -
              Name: sourceCodeCommitAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              OutputArtifacts:
                -
                  Name: SourceOutput
              Configuration:
                RepositoryName: !Ref CodeCommitRepoName
                BranchName: !Ref CodeCommitBranchName
              RunOrder: 1
        - 
          Name: sourceDeployStage
          Actions:
            -
              Name: sourceDeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: S3
              InputArtifacts:
              -
                Name: SourceOutput
              Configuration:
                BucketName: !Ref s3Bucket
                Extract: true
                ObjectKey: !Ref S3KeyPath
              RunOrder: 1

Outputs:
  DestinationBucket:
    Description: Information about the value
    Value: !GetAtt s3Bucket.Arn
